# -*- coding: utf-8 -*-
"""BS_scraper.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18Bwb0gA63n61i6bgp2TPPlL-kbkQP0Sr
"""

# # -*- coding: utf-8 -*-
# """
# EDINET（優先） + TDNet（補完）でBSデータを埋める（テスト用：上から50社だけ）
#
# v24.11:
# - robot home のように「SSR/QSRの prior が年度末(期末)を指すが、その年度末ASRがDAYS_BACK外で拾えない」
#   -> SSR/QSRの prior が年度末 かつ period_end が EDINET走査開始日より前 の場合だけ
#      period_end+30〜+200日を追加探索して ASR を拾い、storeに追加（ASRが優先される）
#   -> これで CP/DB のリース債務省略による誤警告を回避
#
# 従来仕様
# - 空欄セルのみ入力（上書きしない）
# - 入力したセルは黄色
# - 既存値と新値の差が abs(diff) > 1 のセルのみ橙色（警告）
# - EE列に「懸念check」列：行内に橙色が1つでもあれば 1
# """


from __future__ import annotations

import datetime as dt
import io
import os
import random
import re
import time
import zipfile
from collections import Counter, defaultdict
from dataclasses import dataclass
from decimal import Decimal, InvalidOperation, ROUND_HALF_UP
from typing import Dict, List, Optional, Tuple
from urllib.parse import urljoin

import requests
from bs4 import BeautifulSoup
from lxml import etree as ET
from openpyxl import load_workbook
from openpyxl.styles import PatternFill
from openpyxl.utils import column_index_from_string


# =============================
# User settings
# =============================
EDINET_API_KEY = os.environ.get("EDINET_API_KEY", "").strip()

INPUT_XLSX = "データ取得_BS.xlsx"
OUTPUT_XLSX = "データ取得_BS_EDINET優先_TDNet補完_テスト50社_v26_01.xlsx"

MAX_ROWS = 50   # テスト（上から50社）。全社は None

DAYS_BACK_EDINET = 260
DAYS_BACK_TDNET  = 35

SLEEP_EDINET = 0.8
SLEEP_TDNET  = 0.8

WARN_TOLERANCE = Decimal("1.0")  # 百万円単位の差

# HTML補完（加算）に関する安全装置
HTML_ADD_MAX_RATIO_ST = 3.0
HTML_ADD_MAX_RATIO_LT_DEFAULT = 3.0
HTML_ADD_MAX_RATIO_LT_RELAXED = 10.0  # lease_ncl/bond_ncl補完時は緩める

DEBT_SANITY_MARGIN_YEN = 100_000_000  # 1億円ぶんは許容
COMP_MATCH_TOL_YEN = 5_000_000        # 部品一致判定の許容（5百万円）

# 年度末ASRのオンデマンド探索窓（必要時のみ）
ASR_RESCUE_START_DAYS = 30
ASR_RESCUE_END_DAYS   = 200


# =============================
# Constants
# =============================
TDNET_BASE = "https://www.release.tdnet.info/inbs/"
TDNET_UA = "Mozilla/5.0 (compatible; tdnet-xbrl-scraper/edinet-merge-v24_11; +https://example.invalid)"
IX_NS = "http://www.xbrl.org/2008/inlineXBRL"

EDINET_HOST = "https://api.edinet-fsa.go.jp"
EDINET_LIST_EP = EDINET_HOST + "/api/v2/documents.json"
EDINET_DOC_EP  = EDINET_HOST + "/api/v2/documents/{docid}"


# =============================
# Priority / scoring
# =============================
SOURCE_PRI = {"TDNet": 1, "EDINET": 2}
DOC_KIND_PRI = {"OTHER": 0, "SSR": 1, "QSR": 2, "ASR": 3}
SUFFIX_PRI = {"prior": 0, "current": 1}

CORE_FIELDS = [
    "assets_total", "current_assets", "cash_eq_st_invest",
    "current_liabilities", "short_term_borrowings", "long_term_borrowings",
    "income_taxes_payable", "shares_outstanding"
]

def completeness_score(rec: dict) -> int:
    s = 0
    for k in CORE_FIELDS:
        v = rec.get(k)
        if v is None or v == "":
            continue
        s += 1
    return s

def record_priority(rec: dict) -> Tuple[int, int, int, int, dt.datetime]:
    src = SOURCE_PRI.get(rec.get("source", ""), 0)
    dk = DOC_KIND_PRI.get(rec.get("doc_kind", "OTHER"), 0)
    suf = SUFFIX_PRI.get(rec.get("suffix", "prior"), 0)
    comp = rec.get("_completeness", 0)
    as_of = rec.get("as_of") or dt.datetime.min
    return (src, dk, suf, comp, as_of)

def better_than(new: dict, old: Optional[dict]) -> bool:
    if old is None:
        return True
    return record_priority(new) > record_priority(old)


# =============================
# Target BS fields
# =============================
BS_FIELDS = {
    "assets_total": ["jppfs_cor:Assets", "jpigp_cor:AssetsIFRS", "ifrs-full:Assets", "us-gaap:Assets"],
    "current_assets": [
        "jppfs_cor:CurrentAssets",
        "jpigp_cor:CurrentAssetsIFRS",
        "ifrs-full:CurrentAssets",
        "us-gaap:AssetsCurrent",
    ],
    "current_liabilities": [
        "jppfs_cor:CurrentLiabilities",
        "jpigp_cor:TotalCurrentLiabilitiesIFRS",
        "ifrs-full:CurrentLiabilities",
        "us-gaap:LiabilitiesCurrent",
    ],
    "income_taxes_payable": [
        "jppfs_cor:IncomeTaxesPayable",
        "jpigp_cor:IncomeTaxesPayableCLIFRS",
        "ifrs-full:CurrentTaxLiabilities",
        "us-gaap:IncomeTaxesPayableCurrent",
    ],
}

# Cash eq
CASH_EQ_ST_INV_TRUE_TOTAL_CONCEPTS = [
    "jppfs_cor:CashAndCashEquivalentsAndShortTermInvestments",
    "us-gaap:CashAndCashEquivalentsAndShortTermInvestments",
]
CASH_DEPOSITS_CONCEPTS = [
    "jppfs_cor:CashAndDeposits",
    "jppfs_cor:CashAndDepositsSummaryOfBusinessResults",
    "jppfs_cor:CashAndDepositsCA",
]
CASH_EQ_FALLBACK_CONCEPTS = [
    "jppfs_cor:CashAndCashEquivalents",
    "jpigp_cor:CashAndCashEquivalentsIFRS",
    "ifrs-full:CashAndCashEquivalents",
    "us-gaap:CashAndCashEquivalentsAtCarryingValue",
    "us-gaap:CashCashEquivalentsRestrictedCashAndRestrictedCashEquivalents",
]
CASH_EQ_EXTRA_CASH_LOCALNAME_RE = re.compile(r"^(CashDepositsFor|CashAndDepositsFor)", re.IGNORECASE)
CASH_EQ_CALL_LOANS_CONCEPTS = [
    "jppfs_cor:CallLoans",
    "jppfs_cor:CallLoansAssets",
    "jppfs_cor:CallLoansAssetsBNK",
    "jppfs_cor:CallLoansAssetsIOA",
]
CASH_EQ_NONOP_SECURITIES_TOTAL_CONCEPTS = [
    "jppfs_cor:ShortTermInvestmentSecurities",
    "jppfs_cor:MarketableSecurities",
    "jppfs_cor:Securities",
    "ifrs-full:ShortTermInvestments",
    "us-gaap:MarketableSecuritiesCurrent",
    "us-gaap:AvailableForSaleSecuritiesCurrent",
    "us-gaap:TradingSecuritiesCurrent",
]
CASH_EQ_OPERATIONAL_SECURITIES_CONCEPTS = [
    "jppfs_cor:OperationalInvestmentSecuritiesCA",
    "jppfs_cor:OperationalInvestmentSecurities",
    "jppfs_cor:OperatingInvestmentSecurities",
]
RELATED_DEPOSIT_LOCALNAME_RE = re.compile(
    r"Deposits?Paid(?:In|To)(?:SubsidiariesAndAffiliates|RelatedCompanies)",
    re.IGNORECASE,
)
INDUSTRY_SECURITIES_LOCALNAME_RE = re.compile(
    r"SecuritiesFor(?:Banking|Insurance)Business",
    re.IGNORECASE,
)

# Debt
IB_LIAB_CL_TOTAL_CONCEPTS = ["jpigp_cor:InterestBearingLiabilitiesCLIFRS"]
IB_LIAB_NCL_TOTAL_CONCEPTS = ["jpigp_cor:InterestBearingLiabilitiesNCLIFRS"]

BORROWINGS_CL_TOTAL_CONCEPTS = [
    "jpigp_cor:BorrowingsCLIFRS",
    "ifrs-full:BorrowingsCurrent",
    "us-gaap:DebtCurrent",
    "us-gaap:LongTermDebtCurrent",
    "us-gaap:ShortTermBorrowings",
]
BORROWINGS_NCL_TOTAL_CONCEPTS = [
    "jpigp_cor:BorrowingsNCLIFRS",
    "ifrs-full:BorrowingsNoncurrent",
    "us-gaap:LongTermDebtNoncurrent",
    "us-gaap:LongTermDebt",
]

ST_BORROWINGS_DIRECT_CONCEPTS = [
    "jppfs_cor:ShortTermBorrowings",
    "jppfs_cor:ShortTermLoansPayable",
    "jppfs_cor:ShortTermBorrowingsSummaryOfBusinessResults",
    "us-gaap:ShortTermBorrowings",
]

ST_BORROWINGS_TOTAL_ONLY_CONCEPTS = [
    "jppfs_cor:ShortTermBorrowings",
    "us-gaap:ShortTermBorrowings",
]
ST_BORROWINGS_CURRENT_PORTION_CONCEPTS = [
    "jppfs_cor:CurrentPortionOfLongTermLoansPayable",
    "jppfs_cor:CurrentPortionOfLongTermBorrowings",
    "jpigp_cor:CurrentPortionOfLongTermBorrowingsCLIFRS",
    "us-gaap:CurrentMaturitiesOfLongTermDebt",
    "us-gaap:LongTermDebtCurrent",
]
LT_BORROWINGS_DIRECT_CONCEPTS = [
    "jppfs_cor:LongTermBorrowings",
    "jppfs_cor:LongTermLoansPayable",
    "us-gaap:LongTermDebtNoncurrent",
    "us-gaap:LongTermDebt",
    "ifrs-full:BorrowingsNoncurrent",
    "jpigp_cor:BorrowingsNCLIFRS",
]

# Bonds (概念 + ローカル名fallback)
BONDS_CL_TOTAL_CONCEPTS = [
    "jppfs_cor:CurrentPortionOfBonds",
    "jppfs_cor:CurrentPortionOfBondsPayable",
    "jppfs_cor:BondsPayableCL",
    "jppfs_cor:BondsPayableCurrent",
    "jppfs_cor:CurrentPortionOfConvertibleBondTypeBondsWithShareSubscriptionRights",
    "jppfs_cor:ConvertibleBondTypeBondsWithShareSubscriptionRightsCL",
]
BONDS_NCL_TOTAL_CONCEPTS = [
    "jppfs_cor:BondsPayable",
    "jppfs_cor:BondsPayableNCL",
    "jppfs_cor:BondsPayableNoncurrent",
    "jppfs_cor:ConvertibleBondTypeBondsWithShareSubscriptionRights",
    "jppfs_cor:BondsWithShareSubscriptionRights",
    "jppfs_cor:BondsWithSubscriptionRightsToShares",
]
_BOND_LNAME_RE_CL = re.compile(r"(CurrentPortion.*Bonds|BondsPayable.*Current|BondsPayableCL|BondsPayableCurrent)", re.I)
_BOND_LNAME_RE_NCL = re.compile(r"(BondsPayable(?!.*Current)|BondsPayableNCL|BondsPayableNoncurrent|ConvertibleBond|BondsWith)", re.I)
_BOND_LNAME_EXCLUDE = re.compile(r"(Costs|Cost|Discount|Premium|Issue|Issuance|Amort|Interest)", re.I)

LEASE_CL_TOTAL_CONCEPTS = [
    "jppfs_cor:LeaseObligationsCL",
    "jppfs_cor:LeaseObligationsCurrent",
    "ifrs-full:LeaseLiabilitiesCurrent",
    "jpigp_cor:LeaseLiabilitiesCLIFRS",
]
LEASE_CL_COMPONENT_CONCEPTS = ["us-gaap:OperatingLeaseLiabilityCurrent", "us-gaap:FinanceLeaseLiabilityCurrent"]
LEASE_NCL_TOTAL_CONCEPTS = [
    "jppfs_cor:LeaseObligationsNCL",
    "jppfs_cor:LeaseObligationsNoncurrent",
    "ifrs-full:LeaseLiabilitiesNoncurrent",
    "jpigp_cor:LeaseLiabilitiesNCLIFRS",
]
LEASE_NCL_COMPONENT_CONCEPTS = ["us-gaap:OperatingLeaseLiabilityNoncurrent", "us-gaap:FinanceLeaseLiabilityNoncurrent"]

COMMERCIAL_PAPERS_CL_CONCEPTS = ["jppfs_cor:CommercialPapersLiabilities", "CommercialPapersLiabilities"]
COMMERCIAL_PAPERS_LOCAL_RE = re.compile(r"CommercialPapers?Liabilities|CommercialPapers?|CP|ＣＰ|コマーシャル", re.IGNORECASE)

# Related-party short-term loans (e.g., 関係会社短期借入金)
_ST_RELATED_LOANS_LOCAL_RE = re.compile(
    r"ShortTerm(LoansPayable|Borrowings)To(SubsidiariesAndAffiliates|RelatedCompanies|Affiliates|RelatedParties)",
    re.IGNORECASE
)

def _scan_related_st_loans_yen(v_full, ctx: str) -> Optional[int]:
    """Sum related-party short-term loans payable if they exist as separate concepts.

    NOTE: iXBRL and XBRL sometimes provide the same concept twice (prefixed vs unprefixed name).
    Deduplicate by local-name to avoid double count (typical regression: +50m for related-party loans).
    """
    if not ctx:
        return None
    seen = set()
    vals = []
    for (name, c), v in v_full.items():
        if c != ctx or v is None:
            continue
        ln = local_name(name)
        if not _ST_RELATED_LOANS_LOCAL_RE.search(ln):
            continue
        if ln in seen:
            continue
        seen.add(ln)
        vals.append(int(v))
    return int(sum(vals)) if vals else None

SHARES_CONCEPTS = [
    "jppfs_cor:NumberOfIssuedSharesAtTheEndOfFiscalYearIncludingTreasuryStock",
    "jppfs_cor:NumberOfIssuedSharesAtTheEndOfQuarterlyPeriodIncludingTreasuryStock",
    "jppfs_cor:NumberOfIssuedSharesAtTheEndOfPeriodIncludingTreasuryStock",
    "jppfs_cor:NumberOfIssuedSharesAtTheEndOfFiscalYear",
    "jppfs_cor:NumberOfIssuedSharesAtTheEndOfQuarterlyPeriod",
    "jppfs_cor:NumberOfIssuedSharesAtTheEndOfPeriod",
    "ifrs-full:NumberOfSharesIssued",
    "us-gaap:CommonStockSharesIssued",
    "us-gaap:CommonStockSharesOutstanding",
]
FISCAL_YEAR_END_LOCAL_RE = re.compile(r"CurrentFiscalYearEndDateDEI$", re.IGNORECASE)

_FIN_RESULTS_PATTERNS = [
    re.compile(r"決算短信"),
    re.compile(r"\bFinancial\s+Results\b", re.IGNORECASE),
    re.compile(r"\bConsolidated\s+Financial\s+Results\b", re.IGNORECASE),
    re.compile(r"\bQuarterly\s+Financial\s+Results\b", re.IGNORECASE),
]


@dataclass
class Fact:
    name: str
    ctx: Optional[str]
    scale: Optional[str]
    sign: Optional[str]
    txt: str
    kind: str  # ix_nonFraction / ix_nonNumeric / xbrl_numeric / xbrl_nonNumeric


def local_name(concept: str) -> str:
    return concept.split(":", 1)[1] if ":" in concept else concept


def parse_date_any(s: object) -> Optional[dt.date]:
    # v24.11 安定版：period_end の誤パースは四半期マッピング崩れ→誤警告の最大要因なので堅めに。
    if s is None:
        return None
    t = str(s).strip()
    if not t:
        return None

    # 1) ISO / "YYYY-MM-DD..." (EDINET/TDNetで最頻)
    try:
        return dt.date.fromisoformat(t[:10])
    except Exception:
        pass

    # 2) "YYYY/MM/DD" / "YYYY-MM-DD"
    m = re.search(r"(\d{4})[-/](\d{1,2})[-/](\d{1,2})", t)
    if m:
        try:
            return dt.date(int(m.group(1)), int(m.group(2)), int(m.group(3)))
        except Exception:
            return None

    # 3) "YYYYMMDD"（8桁）
    m = re.search(r"(?<!\d)(\d{4})(\d{2})(\d{2})(?!\d)", t)
    if m:
        try:
            return dt.date(int(m.group(1)), int(m.group(2)), int(m.group(3)))
        except Exception:
            return None

    # 4) "YYYY年M月D日"
    m = re.search(r"(\d{4})年\s*(\d{1,2})月\s*(\d{1,2})日", t)
    if m:
        try:
            return dt.date(int(m.group(1)), int(m.group(2)), int(m.group(3)))
        except Exception:
            return None

    return None


def parse_yyyymm(s: object) -> Optional[Tuple[int, int]]:
    if s is None:
        return None
    t = str(s).strip()
    m = re.search(r"(\d{4})\s*[/\-]\s*(\d{1,2})", t)
    if not m:
        return None
    y = int(m.group(1))
    mo = int(m.group(2))
    return (y, mo) if 1 <= mo <= 12 else None


def parse_value_ixbrl(txt: str, scale: Optional[str], sign: Optional[str]) -> Optional[int]:
    if txt is None:
        return None
    s = str(txt).strip()
    if s == "" or s in {"—", "－", "-", "–", "―"}:
        return None
    neg = False
    if s.startswith(("△", "▲")):
        neg = True
        s = s[1:]
    if s.startswith("(") and s.endswith(")"):
        neg = True
        s = s[1:-1]
    s = s.replace(",", "").replace(" ", "").replace("\u3000", "")
    if s.startswith("-"):
        neg = True
        s = s[1:]
    if not re.search(r"\d", s):
        return None
    try:
        d = Decimal(s)
    except InvalidOperation:
        return None
    sc = int(scale) if scale not in (None, "") else 0
    d = d * (Decimal(10) ** sc)
    val = int(d.to_integral_value(rounding=ROUND_HALF_UP))
    return -val if (sign == "-" or neg) else val


def parse_value_xbrl(txt: str) -> Optional[int]:
    if txt is None:
        return None
    s = str(txt).strip()
    if s == "" or s in {"—", "－", "-", "–", "―"}:
        return None
    neg = False
    if s.startswith(("△", "▲")):
        neg = True
        s = s[1:]
    if s.startswith("(") and s.endswith(")"):
        neg = True
        s = s[1:-1]
    s = s.replace(",", "").replace(" ", "").replace("\u3000", "")
    if s.startswith("-"):
        neg = True
        s = s[1:]
    if not re.search(r"\d", s):
        return None
    try:
        d = Decimal(s)
    except InvalidOperation:
        return None
    val = int(d.to_integral_value(rounding=ROUND_HALF_UP))
    return -val if neg else val


def yen_to_million_3dp(v_yen: Optional[int]) -> Optional[float]:
    if v_yen is None:
        return None
    d = (Decimal(v_yen) / Decimal(1_000_000)).quantize(Decimal("0.001"), rounding=ROUND_HALF_UP)
    return float(d)


def sum_nullable(*vals: Optional[int]) -> Optional[int]:
    xs = [v for v in vals if v is not None]
    return int(sum(xs)) if xs else None


def is_blank_cell(v: object) -> bool:
    return v is None or (isinstance(v, str) and v.strip() == "")


def to_decimal_safe(v: object) -> Optional[Decimal]:
    if v is None:
        return None
    if isinstance(v, Decimal):
        return v
    if isinstance(v, int):
        return Decimal(v)
    if isinstance(v, float):
        return Decimal(str(v))
    s = str(v).strip()
    if not s:
        return None
    s = s.replace(",", "")
    try:
        return Decimal(s)
    except Exception:
        return None


def has_fraction_3dp(x: float) -> bool:
    d = Decimal(str(x)).quantize(Decimal("0.001"), rounding=ROUND_HALF_UP)
    return d != d.to_integral_value(rounding=ROUND_HALF_UP)


# -----------------------------
# Context selection
# -----------------------------
def choose_bs_contexts(
    facts: List[Fact],
    ctx_info: Dict[str, dict],
    concept_pool_full: set,
    concept_pool_local: set,
) -> Tuple[Optional[str], Optional[str], Optional[str], Optional[str]]:
    def is_relevant(f: Fact) -> bool:
        if f.kind not in {"ix_nonFraction", "xbrl_numeric"}:
            return False
        return (f.name in concept_pool_full) or (local_name(f.name) in concept_pool_local)

    relevant_ctx = [f.ctx for f in facts if f.ctx and is_relevant(f)]
    used = set(relevant_ctx) if relevant_ctx else set(f.ctx for f in facts if f.ctx)

    freq = Counter([f.ctx for f in facts if f.ctx in used])

    instants = defaultdict(list)
    for cid in used:
        info = ctx_info.get(cid)
        if info and info.get("type") == "instant":
            instants[info.get("instant_date")].append(cid)

    dates = sorted([d for d in instants.keys() if d is not None])
    if not dates:
        return None, None, None, None

    cur_date = dates[-1]
    prior_date = dates[-2] if len(dates) >= 2 else None

    def pick(d: Optional[dt.date]) -> Optional[str]:
        if d is None:
            return None
        cands = instants.get(d, [])
        if not cands:
            return None

        def score(cid: str):
            base = 1 if "member" not in (cid or "").lower() else 0
            return (base, freq.get(cid, 0))

        return max(cands, key=score)

    return (
        prior_date.isoformat() if isinstance(prior_date, dt.date) else None,
        pick(prior_date),
        cur_date.isoformat(),
        pick(cur_date),
    )


def facts_to_value_maps(
    facts: List[Fact],
) -> Tuple[Dict[Tuple[str, str], Optional[int]], Dict[Tuple[str, str], Optional[int]]]:
    v_full: Dict[Tuple[str, str], Optional[int]] = {}
    v_local: Dict[Tuple[str, str], Optional[int]] = {}

    for f in facts:
        if not f.ctx:
            continue
        if f.kind == "ix_nonFraction":
            val = parse_value_ixbrl(f.txt, f.scale, f.sign)
        elif f.kind == "xbrl_numeric":
            val = parse_value_xbrl(f.txt)
        else:
            continue

        kf = (f.name, f.ctx)
        if kf not in v_full:
            v_full[kf] = val

        kl = (local_name(f.name), f.ctx)
        if kl not in v_local:
            v_local[kl] = val

    return v_full, v_local


def first_value(v_full, v_local, concepts: List[str], ctx: Optional[str]) -> Optional[int]:
    if not ctx:
        return None
    for c in concepts:
        v = v_full.get((c, ctx))
        if v is not None:
            return v
    for c in concepts:
        v = v_local.get((local_name(c), ctx))
        if v is not None:
            return v
    return None


def sum_for_concepts(v_full, v_local, concepts: List[str], ctx: Optional[str]) -> Optional[int]:
    if not ctx:
        return None
    vals = []
    for c in concepts:
        v = v_full.get((c, ctx))
        if v is None:
            v = v_local.get((local_name(c), ctx))
        if v is not None:
            vals.append(v)
    return int(sum(vals)) if vals else None


def max_for_concepts(v_full, v_local, concepts: List[str], ctx: Optional[str]) -> Optional[int]:
    if not ctx:
        return None
    vals = []
    for c in concepts:
        v = v_full.get((c, ctx))
        if v is None:
            v = v_local.get((local_name(c), ctx))
        if v is not None:
            vals.append(v)
    return int(max(vals)) if vals else None


def scan_sum_by_localname(v_full, ctx: str, pred) -> Optional[int]:
    vals = []
    for (name, c), v in v_full.items():
        if c != ctx or v is None:
            continue
        if pred(local_name(name)):
            vals.append(v)
    return int(sum(vals)) if vals else None


def scan_max_by_localname(v_full, ctx: str, include_re: re.Pattern, exclude_re: Optional[re.Pattern] = None) -> Optional[int]:
    vals = []
    for (name, c), v in v_full.items():
        if c != ctx or v is None:
            continue
        ln = local_name(name)
        if exclude_re and exclude_re.search(ln):
            continue
        if include_re.search(ln):
            vals.append(v)
    return int(max(vals)) if vals else None


def extract_fy_end_month_from_dei(facts: List[Fact]) -> Optional[int]:
    for f in facts:
        if f.kind not in {"ix_nonNumeric", "xbrl_nonNumeric"}:
            continue
        if FISCAL_YEAR_END_LOCAL_RE.search(local_name(f.name)):
            d = parse_date_any(f.txt)
            if d is not None and 1 <= d.month <= 12:
                return d.month
    return None


# -----------------------------
# Cash eq calc
# -----------------------------
def calc_cash_eq_st_invest(v_full, v_local, ctx: Optional[str]) -> Optional[int]:
    if not ctx:
        return None

    cash = first_value(v_full, v_local, CASH_DEPOSITS_CONCEPTS, ctx)
    if cash is None:
        cash = first_value(v_full, v_local, CASH_EQ_FALLBACK_CONCEPTS, ctx)

    extra_cash = scan_sum_by_localname(v_full, ctx, lambda ln: bool(CASH_EQ_EXTRA_CASH_LOCALNAME_RE.search(ln)))
    call_loans = max_for_concepts(v_full, v_local, CASH_EQ_CALL_LOANS_CONCEPTS, ctx)
    related_deposits = scan_sum_by_localname(v_full, ctx, lambda ln: bool(RELATED_DEPOSIT_LOCALNAME_RE.search(ln)))

    nonop_total = max_for_concepts(v_full, v_local, CASH_EQ_NONOP_SECURITIES_TOTAL_CONCEPTS, ctx)
    if nonop_total is None:
        nonop_total = scan_sum_by_localname(v_full, ctx, lambda ln: bool(INDUSTRY_SECURITIES_LOCALNAME_RE.search(ln)))

    op = sum_for_concepts(v_full, v_local, CASH_EQ_OPERATIONAL_SECURITIES_CONCEPTS, ctx)

    component_based = sum_nullable(cash, extra_cash, call_loans, related_deposits, nonop_total, op)
    if component_based is not None:
        return component_based

    total = first_value(v_full, v_local, CASH_EQ_ST_INV_TRUE_TOTAL_CONCEPTS, ctx)
    return total


# -----------------------------
# Debt calc helpers
# -----------------------------
def _scan_sum_regex(v_full, ctx: str, include_re: re.Pattern) -> Optional[int]:
    vals = []
    for (name, c), v in v_full.items():
        if c != ctx or v is None:
            continue
        lname = local_name(name)
        if include_re.search(lname):
            vals.append(v)
    return int(sum(vals)) if vals else None


def calc_lease_current(v_full, v_local, ctx: Optional[str]) -> Optional[int]:
    if not ctx:
        return None
    total = first_value(v_full, v_local, LEASE_CL_TOTAL_CONCEPTS, ctx)
    if total is not None:
        return total
    return sum_for_concepts(v_full, v_local, LEASE_CL_COMPONENT_CONCEPTS, ctx)


def calc_lease_noncurrent(v_full, v_local, ctx: Optional[str]) -> Optional[int]:
    if not ctx:
        return None
    total = first_value(v_full, v_local, LEASE_NCL_TOTAL_CONCEPTS, ctx)
    if total is not None:
        return total
    return sum_for_concepts(v_full, v_local, LEASE_NCL_COMPONENT_CONCEPTS, ctx)


def calc_bonds_current(v_full, v_local, ctx: Optional[str]) -> Optional[int]:
    if not ctx:
        return None
    v = first_value(v_full, v_local, BONDS_CL_TOTAL_CONCEPTS, ctx)
    if v is not None:
        return v
    return scan_max_by_localname(v_full, ctx, include_re=_BOND_LNAME_RE_CL, exclude_re=_BOND_LNAME_EXCLUDE)


def calc_bonds_noncurrent(v_full, v_local, ctx: Optional[str]) -> Optional[int]:
    if not ctx:
        return None
    v = first_value(v_full, v_local, BONDS_NCL_TOTAL_CONCEPTS, ctx)
    if v is not None:
        return v
    return scan_max_by_localname(v_full, ctx, include_re=_BOND_LNAME_RE_NCL, exclude_re=_BOND_LNAME_EXCLUDE)


def calc_commercial_papers_current(v_full, v_local, ctx: Optional[str]) -> Optional[int]:
    if not ctx:
        return None
    v = first_value(v_full, v_local, COMMERCIAL_PAPERS_CL_CONCEPTS, ctx)
    if v is not None:
        return v
    return _scan_sum_regex(v_full, ctx, include_re=COMMERCIAL_PAPERS_LOCAL_RE)


def should_add_current_portion_when_total_exists(
    borrow_total: int,
    st_direct: Optional[int],
    cur_port: int,
    tol_yen: int = 1_000_000,
) -> bool:
    if st_direct is not None:
        if abs(borrow_total - (st_direct + cur_port)) <= tol_yen:
            return False
    return True

def extract_debt_components_xbrl(v_full, v_local, ctx: Optional[str]) -> dict:
    if not ctx:
        return {
            "loans_cl": None, "bonds_cl": None, "cp_cl": None, "lease_cl": None, "st_total": None,
            "loans_ncl": None, "bonds_ncl": None, "lease_ncl": None, "lt_total": None,
        }

    ibl_cl = first_value(v_full, v_local, IB_LIAB_CL_TOTAL_CONCEPTS, ctx)
    ibl_ncl = first_value(v_full, v_local, IB_LIAB_NCL_TOTAL_CONCEPTS, ctx)

    cur_port = first_value(v_full, v_local, ST_BORROWINGS_CURRENT_PORTION_CONCEPTS, ctx)

    # Main short-term borrowing concept:
    # - If ShortTermBorrowings is tagged, treat it as TOTAL (do not add related-party breakdown).
    # - Otherwise fall back to ShortTermLoansPayable etc, where related-party may be a separate line item.
    st_total_like = first_value(v_full, v_local, ST_BORROWINGS_TOTAL_ONLY_CONCEPTS, ctx)
    st_direct = st_total_like
    st_direct_is_total = (st_total_like is not None)
    if st_direct is None:
        st_direct = first_value(v_full, v_local, [
            "jppfs_cor:ShortTermLoansPayable",
            "jppfs_cor:ShortTermBorrowingsSummaryOfBusinessResults",
        ], ctx)

    # Related-party short-term loans are often tagged separately (e.g., Chugai Mining)
    st_related = _scan_related_st_loans_yen(v_full, ctx)

    total_cl = first_value(v_full, v_local, BORROWINGS_CL_TOTAL_CONCEPTS, ctx)
    if total_cl is not None:
        # If total current borrowings exists, trust it (and optionally add cur_port if not included)
        loans_cl = total_cl
        if cur_port is not None and should_add_current_portion_when_total_exists(total_cl, st_direct, cur_port):
            loans_cl = total_cl + cur_port
    else:
        # No total -> build from components.
        # Add related-party ST loans *as separate line item* when present.
        # v24.11方針：総額（ShortTermBorrowings等）がある文脈では内訳（related-party）を足さない（重複防止）
        if st_direct is None:
            loans_cl = sum_nullable(st_direct, cur_port, st_related)
        else:
            # If st_direct is TOTAL (ShortTermBorrowings), related-party is usually breakdown -> do not add.
            # If st_direct is ShortTermLoansPayable etc, related-party may be separate line item -> add.
            if st_direct_is_total:
                loans_cl = sum_nullable(st_direct, cur_port)
            else:
                loans_cl = sum_nullable(st_direct, cur_port, st_related)

    total_ncl = first_value(v_full, v_local, BORROWINGS_NCL_TOTAL_CONCEPTS, ctx)
    if total_ncl is not None:
        loans_ncl = total_ncl
    else:
        loans_ncl = first_value(v_full, v_local, LT_BORROWINGS_DIRECT_CONCEPTS, ctx)

    bonds_cl = calc_bonds_current(v_full, v_local, ctx)
    cp_cl = calc_commercial_papers_current(v_full, v_local, ctx)
    lease_cl = calc_lease_current(v_full, v_local, ctx)

    bonds_ncl = calc_bonds_noncurrent(v_full, v_local, ctx)
    lease_ncl = calc_lease_noncurrent(v_full, v_local, ctx)

    st_total = ibl_cl if ibl_cl is not None else sum_nullable(loans_cl, bonds_cl, cp_cl, lease_cl)
    lt_total = ibl_ncl if ibl_ncl is not None else sum_nullable(loans_ncl, bonds_ncl, lease_ncl)

    return {
        "loans_cl": loans_cl, "bonds_cl": bonds_cl, "cp_cl": cp_cl, "lease_cl": lease_cl, "st_total": st_total,
        "loans_ncl": loans_ncl, "bonds_ncl": bonds_ncl, "lease_ncl": lease_ncl, "lt_total": lt_total,
    }

def extract_debt_and_lease(v_full, v_local, ctx: Optional[str]) -> Tuple[Optional[int], Optional[int]]:
    comps = extract_debt_components_xbrl(v_full, v_local, ctx)
    return comps.get("st_total"), comps.get("lt_total")


def extract_shares(v_full, v_local, ctx: Optional[str]) -> Optional[int]:
    if not ctx:
        return None
    v = first_value(v_full, v_local, SHARES_CONCEPTS, ctx)
    if v is not None:
        return v
    cand = []
    for (lname, c), val in v_local.items():
        if c == ctx and val is not None and "NumberOfIssuedShares" in lname:
            cand.append((lname, val))
    if cand:
        cand.sort(key=lambda x: (("IncludingTreasuryStock" in x[0]), len(x[0])), reverse=True)
        return cand[0][1]
    return None


# -----------------------------
# Debt context selection
# -----------------------------
def _debt_components(v_full, v_local, ctx: str) -> dict:
    comps = extract_debt_components_xbrl(v_full, v_local, ctx)
    st = comps.get("st_total")
    loans = comps.get("loans_cl")
    lease = comps.get("lease_cl")
    bonds = comps.get("bonds_cl")
    cp = comps.get("cp_cl")
    return {
        "ctx": ctx,
        "st": st,
        "component_count": sum(1 for x in [loans, lease, bonds, cp] if x is not None),
    }


def pick_best_debt_context(
    target_date: Optional[dt.date],
    primary_ctx: Optional[str],
    ctx_info: Dict[str, dict],
    v_full,
    v_local,
) -> Optional[str]:
    # 回帰対策：まず BS primary_ctx を優先し、明確に不正な場合のみ同日別ctxへフォールバックする。
    if not target_date:
        return primary_ctx

    def _is_sane(cid: Optional[str]) -> bool:
        if not cid:
            return False
        info = ctx_info.get(cid) or {}
        if info.get("type") != "instant" or info.get("instant_date") != target_date:
            return False
        comps = _debt_components(v_full, v_local, cid)
        st = comps.get("st")
        if st is None or st < 0:
            return False
        cur_liab = first_value(v_full, v_local, BS_FIELDS["current_liabilities"], cid)
        if cur_liab is not None and st > cur_liab + DEBT_SANITY_MARGIN_YEN:
            return False
        return True

    # 1) primary_ctx が同日のinstantで妥当ならそれを採用
    if _is_sane(primary_ctx):
        return primary_ctx

    # 2) 同日候補からスコアで選ぶ
    candidates = [cid for cid, info in ctx_info.items()
                  if info.get("type") == "instant" and info.get("instant_date") == target_date]
    if not candidates:
        return primary_ctx

    best = None
    best_score = None

    for cid in candidates:
        if not _is_sane(cid):
            continue

        comps = _debt_components(v_full, v_local, cid)
        st = int(comps.get("st") or 0)

        low = (cid or "").lower()
        not_noncon = 1 if "nonconsolidated" not in low else 0
        has_con = 1 if ("consolidated" in low and "nonconsolidated" not in low) else 0
        no_member = 1 if "member" not in low else 0
        comp_cnt = int(comps.get("component_count") or 0)

        score = (has_con, not_noncon, no_member, comp_cnt, st)

        if best is None or score > best_score:
            best = cid
            best_score = score

    return best if best is not None else primary_ctx


# =============================
# HTML debt schedule parsing (ASRのみ適用：既存の安定版)
# =============================
def _parse_int_from_cell(s: str) -> Optional[int]:
    if s is None:
        return None
    t = str(s).strip()
    if t == "" or t in {"－", "—", "-", "–", "―"}:
        return None
    neg = False
    if t.startswith("(") and t.endswith(")"):
        neg = True
        t = t[1:-1]
    t = t.replace(",", "").replace(" ", "").replace("\u3000", "")
    if t.startswith("-"):
        neg = True
        t = t[1:]
    if not re.search(r"\d", t):
        return None
    try:
        v = int(Decimal(t).to_integral_value(rounding=ROUND_HALF_UP))
    except Exception:
        return None
    return -v if neg else v


def _detect_unit_and_explicit(text: str) -> Tuple[str, bool]:
    if "百万円" in text:
        return "百万円", True
    if "千円" in text:
        return "千円", True
    if "円" in text:
        return "円", True
    return "百万円", False


def _raw_to_yen(raw: Optional[int], unit: str) -> Optional[int]:
    if raw is None:
        return None
    if unit == "百万円":
        return int(raw) * 1_000_000
    if unit == "千円":
        return int(raw) * 1_000
    if unit == "円":
        return int(raw)
    return int(raw) * 1_000_000


_ONE_YEAR_RE = re.compile(r"(１年|1年).*(以内|内)", re.I)
_EXCLUDE_RE  = re.compile(r"(除く|excluding)", re.I)
_LOAN_RE     = re.compile(r"(借入|ローン|Loans?)", re.I)
_LEASE_RE    = re.compile(r"リース(債務|負債)", re.I)
_CP_RE       = re.compile(r"コマーシャル|ＣＰ|CP", re.I)
_BOND_RE     = re.compile(r"(社債|転換社債|新株予約権付社債|CB)", re.I)

_HDR_START_RE = re.compile(r"(当期首残高|期首残高|前期末残高|前期末|前連結会計年度末|前事業年度末|期首)", re.I)
_HDR_END_RE   = re.compile(r"(当期末残高|期末残高|当期末|期末|当連結会計年度末|当事業年度末)", re.I)
_HDR_RATE_RE  = re.compile(r"(利率|％|%|平均利率)", re.I)

def _pick_date_columns(matrix: List[List[str]]) -> Tuple[Optional[int], Optional[int]]:
    if not matrix:
        return None, None

    max_cols = max(len(r) for r in matrix[:3]) if matrix else 0
    headers_by_col = []
    for c in range(max_cols):
        parts = []
        for r in matrix[:3]:
            if c < len(r):
                s = str(r[c]).strip()
                if s:
                    parts.append(s)
        headers_by_col.append(" ".join(parts))

    end_col = None
    start_col = None
    for c, h in enumerate(headers_by_col):
        if end_col is None and _HDR_END_RE.search(h):
            end_col = c
    for c, h in enumerate(headers_by_col):
        if start_col is None and _HDR_START_RE.search(h):
            start_col = c

    if end_col is not None:
        if start_col is not None and start_col != end_col:
            return start_col, end_col
        if end_col - 1 >= 0:
            return end_col - 1, end_col

    body = matrix[1:] if len(matrix) > 1 else []
    max_cols2 = max(len(r) for r in body) if body else max_cols
    if max_cols2 <= 0:
        return None, None

    header_text = {}
    for c in range(max_cols2):
        parts = []
        for r in matrix[:3]:
            if c < len(r):
                s = str(r[c]).strip()
                if s:
                    parts.append(s)
        header_text[c] = " ".join(parts)

    scores = []
    for c in range(max_cols2):
        cnt = 0
        for r in body:
            if c >= len(r):
                continue
            v = _parse_int_from_cell(r[c])
            if v is not None:
                cnt += 1
        penalty = 2 if _HDR_RATE_RE.search(header_text.get(c, "")) else 0
        scores.append((cnt - penalty, c))

    scores.sort(key=lambda x: (x[0], x[1]))
    best = [c for s, c in scores if s > 0]
    if not best:
        return None, None
    end_col = best[-1]
    start_col = best[-2] if len(best) >= 2 else None
    return start_col, end_col


def extract_debt_schedules_from_html(html: str) -> List[dict]:
    out = []
    if not html or "<table" not in html:
        return out
    if "借入金等明細表" not in html:
        return out

    soup = BeautifulSoup(html, "lxml")
    tables = soup.find_all("table")
    if not tables:
        return out

    for t in tables:
        txt = t.get_text(" ", strip=True)
        if "借入金等明細表" not in txt and ("短期借入金" not in txt and "長期借入金" not in txt):
            continue

        matrix = []
        for tr in t.find_all("tr"):
            row = [c.get_text(" ", strip=True) for c in tr.find_all(["th", "td"])]
            if row:
                matrix.append(row)
        if len(matrix) < 2:
            continue

        unit_hint, unit_explicit = _detect_unit_and_explicit(txt + " " + " ".join(matrix[0]))
        _, end_col = _pick_date_columns(matrix)
        if end_col is None:
            continue

        st_end = {}
        lt_end = {}

        for row in matrix[1:]:
            if len(row) <= end_col:
                continue
            label = row[0]
            v_end = _parse_int_from_cell(row[end_col])
            if v_end is None:
                continue

            exclude_flag = bool(_EXCLUDE_RE.search(label))
            one_year = bool(_ONE_YEAR_RE.search(label))

            if _CP_RE.search(label):
                st_end["cp"] = v_end
                continue

            if "短期借入" in label:
                st_end["short_loan"] = int(st_end.get("short_loan") or 0) + int(v_end)
                continue

            if _LEASE_RE.search(label):
                if exclude_flag or (not one_year):
                    lt_end.setdefault("lease_ncl", v_end)
                else:
                    st_end.setdefault("lease", v_end)
                continue

            if _BOND_RE.search(label):
                if exclude_flag or (not one_year):
                    lt_end.setdefault("bond_ncl", v_end)
                else:
                    st_end.setdefault("cur_bond", v_end)
                continue

            if _LOAN_RE.search(label):
                if one_year and (not exclude_flag) and ("長期" in label or "ノンリコース" in label or "Nonrecourse" in label):
                    st_end.setdefault("cur_lt_loan", v_end)
                else:
                    if ("長期" in label) or exclude_flag:
                        lt_end.setdefault("long_loan", v_end)
                continue

        st_end_raw = sum(v for v in st_end.values() if v is not None) if st_end else None
        lt_end_raw = sum(v for v in lt_end.values() if v is not None) if lt_end else None

        if st_end_raw is None and lt_end_raw is None:
            continue

        score = 0
        score += 3 * len(st_end)
        score += 3 * len(lt_end)
        score += 2 if unit_explicit else 0

        out.append({
            "unit_hint": unit_hint,
            "unit_explicit": unit_explicit,
            "st_end_raw": st_end_raw,
            "lt_end_raw": lt_end_raw,
            "st_end_components": st_end,
            "lt_end_components": lt_end,
            "_score": score,
        })

    out.sort(key=lambda x: x.get("_score", 0), reverse=True)
    return out[:30]

_BOND_TABLE_HINT_RE = re.compile(r"(社債|転換社債|新株予約権付社債|CB|Bonds?)", re.IGNORECASE)

def extract_bond_maturity_1y_from_html(html: str) -> List[dict]:
    out = []
    if not html or "<table" not in html:
        return out
    soup = BeautifulSoup(html, "lxml")

    for tbl in soup.find_all("table"):
        tbl_text = tbl.get_text(" ", strip=True)
        # ★重要：社債テーブル以外（借入金の年限表など）を除外
        if not _BOND_TABLE_HINT_RE.search(tbl_text):
            continue

        matrix = []
        for tr in tbl.find_all("tr"):
            row = [c.get_text(" ", strip=True) for c in tr.find_all(["th", "td"])]
            if row:
                matrix.append(row)
        if not matrix:
            continue

        header_text = " ".join(matrix[0])
        if ("１年以内" not in header_text and "1年以内" not in header_text):
            continue
        if not _BOND_MATURITY_HDR_RE.search(" ".join(matrix[0])):
            continue

        unit_hint, unit_explicit = _detect_unit_and_explicit(" ".join(matrix[0]) + " " + tbl_text)

        col_1y = None
        for j, cell in enumerate(matrix[0]):
            if "１年以内" in cell or "1年以内" in cell:
                col_1y = j
                break
        if col_1y is None:
            continue

        total_val = None
        for r in matrix[1:]:
            if col_1y >= len(r):
                continue
            if r and ("合計" in r[0] or "Total" in r[0]):
                v = _parse_int_from_cell(r[col_1y])
                if v is not None:
                    total_val = v
                    break

        if total_val is None:
            s = 0
            cnt = 0
            for r in matrix[1:]:
                if col_1y >= len(r):
                    continue
                v = _parse_int_from_cell(r[col_1y])
                if v is None:
                    continue
                s += v
                cnt += 1
            if cnt <= 0:
                continue
            total_val = s

        yen = _raw_to_yen(total_val, unit_hint)
        if yen is None or yen <= 0:
            continue

        out.append({
            "raw_1y": total_val,
            "unit_hint": unit_hint,
            "unit_explicit": unit_explicit,
            "yen_1y": yen,
            "_score": (10 if unit_explicit else 0) + 5,
        })

    out.sort(key=lambda x: x.get("_score", 0), reverse=True)
    return out[:10]

# =============================
# ZIP parsing (EDINET/TDNet共通)
# =============================
def parse_zip_any(zip_bytes: bytes) -> Tuple[Dict[str, dict], List[Fact], List[str]]:
    ctx_all: Dict[str, dict] = {}
    facts_all: List[Fact] = []
    html_candidates: List[str] = []

    parser = ET.XMLParser(recover=True, huge_tree=True)

    def parse_ixbrl_doc(xml_bytes: bytes) -> Tuple[Dict[str, dict], List[Fact]]:
        root = ET.fromstring(xml_bytes, parser=parser)

        ctxs: Dict[str, dict] = {}
        for ctx in root.xpath('//*[local-name()="context"]'):
            cid = ctx.get("id")
            if not cid:
                continue
            period = ctx.xpath('./*[local-name()="period"]')
            if not period:
                continue
            period = period[0]
            inst = period.xpath('./*[local-name()="instant"]/text()')
            if inst:
                ctxs[cid] = {"type": "instant", "instant_date": parse_date_any(inst[0].strip())}
                continue
            start = period.xpath('./*[local-name()="startDate"]/text()')
            end = period.xpath('./*[local-name()="endDate"]/text()')
            if start and end:
                ctxs[cid] = {"type": "duration", "start_date": parse_date_any(start[0].strip()), "end_date": parse_date_any(end[0].strip())}

        facts: List[Fact] = []
        for el in root.xpath('//*[local-name()="nonFraction" and namespace-uri()=$ix]', ix=IX_NS):
            name = el.get("name")
            if not name:
                continue
            facts.append(Fact(
                name=name,
                ctx=el.get("contextRef") or el.get("contextref"),
                scale=el.get("scale"),
                sign=el.get("sign"),
                txt="".join(el.itertext()).strip(),
                kind="ix_nonFraction",
            ))
        for el in root.xpath('//*[local-name()="nonNumeric" and namespace-uri()=$ix]', ix=IX_NS):
            name = el.get("name")
            if not name:
                continue
            facts.append(Fact(
                name=name,
                ctx=el.get("contextRef") or el.get("contextref"),
                scale=None,
                sign=None,
                txt="".join(el.itertext()).strip(),
                kind="ix_nonNumeric",
            ))
        return ctxs, facts

    def parse_xbrl_instance(xml_bytes: bytes) -> Tuple[Dict[str, dict], List[Fact]]:
        root = ET.fromstring(xml_bytes, parser=parser)

        ctxs: Dict[str, dict] = {}
        for ctx in root.xpath('//*[local-name()="context"]'):
            cid = ctx.get("id")
            if not cid:
                continue
            period = ctx.xpath('./*[local-name()="period"]')
            if not period:
                continue
            period = period[0]
            inst = period.xpath('./*[local-name()="instant"]/text()')
            if inst:
                ctxs[cid] = {"type": "instant", "instant_date": parse_date_any(inst[0].strip())}
                continue
            start = period.xpath('./*[local-name()="startDate"]/text()')
            end = period.xpath('./*[local-name()="endDate"]/text()')
            if start and end:
                ctxs[cid] = {"type": "duration", "start_date": parse_date_any(start[0].strip()), "end_date": parse_date_any(end[0].strip())}

        facts: List[Fact] = []
        for el in root.xpath('//*[@contextRef]'):
            if el.tag is None:
                continue
            ln = ET.QName(el).localname
            ctx = el.get("contextRef")
            txt = (el.text or "").strip()
            if el.get("unitRef") is not None:
                facts.append(Fact(name=ln, ctx=ctx, scale=None, sign=None, txt=txt, kind="xbrl_numeric"))
            else:
                if FISCAL_YEAR_END_LOCAL_RE.search(ln):
                    facts.append(Fact(name=ln, ctx=ctx, scale=None, sign=None, txt=txt, kind="xbrl_nonNumeric"))
        return ctxs, facts

    with zipfile.ZipFile(io.BytesIO(zip_bytes)) as zf:
        for info in zf.infolist():
            low = info.filename.lower()

            if low.endswith((".htm", ".html", ".xhtml")):
                b = zf.read(info)
                try:
                    text = b.decode("utf-8", "ignore")
                except Exception:
                    text = ""
                if "<table" in text:
                    html_candidates.append(text)

                if (b.find(b"nonFraction") != -1) and (b.find(b"xmlns:ix") != -1 or b.find(b"<ix:") != -1):
                    try:
                        ctxs, facts = parse_ixbrl_doc(b)
                        ctx_all.update(ctxs)
                        facts_all.extend(facts)
                    except Exception:
                        pass
                continue

            if low.endswith(".xbrl"):
                b = zf.read(info)
                if b"<xbrl" not in b[:5000].lower():
                    continue
                try:
                    ctxs, facts = parse_xbrl_instance(b)
                    ctx_all.update(ctxs)
                    facts_all.extend(facts)
                except Exception:
                    pass

    return ctx_all, facts_all, html_candidates


# =============================
# ASR HTML補完（欠け部品だけ加算）
# =============================
def _yen_unit_multiplier(unit_hint: str) -> int:
    if unit_hint == "百万円":
        return 1_000_000
    if unit_hint == "千円":
        return 1_000
    if unit_hint == "円":
        return 1
    return 1_000_000


def _component_dict_to_yen(comps_raw: dict, unit_hint: str) -> dict:
    mul = _yen_unit_multiplier(unit_hint)
    out = {}
    for k, v in (comps_raw or {}).items():
        if v is None:
            continue
        out[k] = int(v) * mul
    return out


def _close(a: Optional[int], b: Optional[int], tol: int = COMP_MATCH_TOL_YEN) -> bool:
    if a is None or b is None:
        return False
    return abs(int(a) - int(b)) <= tol


def _apply_html_additive_adjustment_for_asr(
    out: dict,
    v_full, v_local,
    debt_ctx: str,
    html_candidates: List[str],
) -> None:
    x = extract_debt_components_xbrl(v_full, v_local, debt_ctx)
    xbrl_st = x.get("st_total")
    xbrl_lt = x.get("lt_total")
    xbrl_loans_cl = x.get("loans_cl")
    xbrl_bonds_cl = x.get("bonds_cl")
    xbrl_cp_cl = x.get("cp_cl")
    xbrl_lease_cl = x.get("lease_cl")
    xbrl_loans_ncl = x.get("loans_ncl")
    xbrl_bonds_ncl = x.get("bonds_ncl")
    xbrl_lease_ncl = x.get("lease_ncl")

    schedules: List[dict] = []
    for h in html_candidates:
        schedules.extend(extract_debt_schedules_from_html(h))
    if not schedules:
        return

    st_sch = None
    lt_sch = None
    for sch in schedules:
        stc = sch.get("st_end_components") or {}
        ltc = sch.get("lt_end_components") or {}
        if st_sch is None and (("short_loan" in stc) or ("cur_lt_loan" in stc) or ("lease" in stc) or ("cp" in stc)):
            st_sch = sch
        if lt_sch is None and (("long_loan" in ltc) or ("lease_ncl" in ltc) or ("bond_ncl" in ltc)):
            lt_sch = sch
        if st_sch and lt_sch:
            break

    # Short-term
    if st_sch:
        unit_hint = st_sch.get("unit_hint", "百万円")
        st_html_yen = _component_dict_to_yen(st_sch.get("st_end_components", {}), unit_hint)
        html_loans_sum = sum_nullable(st_html_yen.get("short_loan"), st_html_yen.get("cur_lt_loan"))
        loans_sum_matches = _close(xbrl_loans_cl, html_loans_sum)

        missing_add = 0
        if st_html_yen.get("lease") not in (None, 0) and (xbrl_lease_cl in (None, 0)):
            missing_add += int(st_html_yen["lease"])
        if st_html_yen.get("cp") not in (None, 0) and (xbrl_cp_cl in (None, 0)):
            missing_add += int(st_html_yen["cp"])
        if st_html_yen.get("cur_bond") not in (None, 0) and (xbrl_bonds_cl in (None, 0)):
            missing_add += int(st_html_yen["cur_bond"])
        if (not loans_sum_matches) and st_html_yen.get("cur_lt_loan") not in (None, 0):
            if xbrl_loans_cl is None:
                missing_add += int(st_html_yen["cur_lt_loan"])

        if missing_add > 0:
            base = int(xbrl_st) if xbrl_st is not None else 0
            new_st = base + missing_add
            if xbrl_st is None or new_st <= int(xbrl_st) * HTML_ADD_MAX_RATIO_ST:
                cur_liab = first_value(v_full, v_local, BS_FIELDS["current_liabilities"], debt_ctx)
                if cur_liab is None or new_st <= int(cur_liab) + DEBT_SANITY_MARGIN_YEN:
                    out["short_term_borrowings_current"] = new_st

    # Long-term
    if lt_sch:
        unit_hint = lt_sch.get("unit_hint", "百万円")
        lt_html_yen = _component_dict_to_yen(lt_sch.get("lt_end_components", {}), unit_hint)

        missing_add = 0
        add_lease = (lt_html_yen.get("lease_ncl") not in (None, 0) and (xbrl_lease_ncl in (None, 0)))
        add_bond  = (lt_html_yen.get("bond_ncl") not in (None, 0) and (xbrl_bonds_ncl in (None, 0)))

        if add_lease:
            missing_add += int(lt_html_yen["lease_ncl"])
        if add_bond:
            missing_add += int(lt_html_yen["bond_ncl"])
        if lt_html_yen.get("long_loan") not in (None, 0) and xbrl_loans_ncl is None:
            missing_add += int(lt_html_yen["long_loan"])

        if missing_add > 0:
            base = int(xbrl_lt) if xbrl_lt is not None else 0
            new_lt = base + missing_add
            max_ratio = HTML_ADD_MAX_RATIO_LT_RELAXED if (add_lease or add_bond) else HTML_ADD_MAX_RATIO_LT_DEFAULT
            if xbrl_lt is None or new_lt <= int(xbrl_lt) * max_ratio:
                out["long_term_borrowings_current"] = new_lt

    # Bond maturity schedule 1y add（cur_bond が無い場合のみ）
    cur_bond_present = (xbrl_bonds_cl not in (None, 0))
    if st_sch:
        stc = st_sch.get("st_end_components") or {}
        if stc.get("cur_bond") not in (None, 0):
            cur_bond_present = True

    if not cur_bond_present:
        bond_cands: List[dict] = []
        for h in html_candidates:
            bond_cands.extend(extract_bond_maturity_1y_from_html(h))
        if bond_cands:
            bond_1y_yen = bond_cands[0].get("yen_1y")
            if isinstance(bond_1y_yen, int) and bond_1y_yen > 0:
                cur_st = out.get("short_term_borrowings_current")
                if cur_st is None:
                    out["short_term_borrowings_current"] = bond_1y_yen
                else:
                    out["short_term_borrowings_current"] = int(cur_st) + int(bond_1y_yen)

    # --- Prefer schedule totals when the selected debt_ctx is nonconsolidated ---
    # Some filers tag debt only in NonConsolidatedMember contexts, while the schedule table is consolidated.
    # In that case, schedule totals are usually closer to what the Excel expects.
    if "nonconsolidated" in (debt_ctx or "").lower():
        if st_sch:
            unit_hint = st_sch.get("unit_hint", "百万円")
            st_total_yen = _raw_to_yen(st_sch.get("st_end_raw"), unit_hint)
            if isinstance(st_total_yen, int) and st_total_yen >= 0:
                cur_liab = first_value(v_full, v_local, BS_FIELDS["current_liabilities"], debt_ctx)
                if cur_liab is None or st_total_yen <= int(cur_liab) + DEBT_SANITY_MARGIN_YEN:
                    out["short_term_borrowings_current"] = st_total_yen

        if lt_sch:
            unit_hint = lt_sch.get("unit_hint", "百万円")
            lt_total_yen = _raw_to_yen(lt_sch.get("lt_end_raw"), unit_hint)
            if isinstance(lt_total_yen, int) and lt_total_yen >= 0:
                out["long_term_borrowings_current"] = lt_total_yen

# =============================
# Process ZIP -> extracted values
# =============================
def process_one_zip(zip_bytes: bytes, doc_kind: Optional[str] = None) -> Dict[str, object]:
    ctx_info, facts, html_candidates = parse_zip_any(zip_bytes)

    bs_full = set(sum(BS_FIELDS.values(), []))
    extra_full = set(
        IB_LIAB_CL_TOTAL_CONCEPTS + IB_LIAB_NCL_TOTAL_CONCEPTS
        + BORROWINGS_CL_TOTAL_CONCEPTS + BORROWINGS_NCL_TOTAL_CONCEPTS
        + ST_BORROWINGS_DIRECT_CONCEPTS + ST_BORROWINGS_CURRENT_PORTION_CONCEPTS + LT_BORROWINGS_DIRECT_CONCEPTS
        + BONDS_CL_TOTAL_CONCEPTS + BONDS_NCL_TOTAL_CONCEPTS
        + LEASE_CL_TOTAL_CONCEPTS + LEASE_CL_COMPONENT_CONCEPTS + LEASE_NCL_TOTAL_CONCEPTS + LEASE_NCL_COMPONENT_CONCEPTS
        + COMMERCIAL_PAPERS_CL_CONCEPTS
        + SHARES_CONCEPTS
        + CASH_EQ_ST_INV_TRUE_TOTAL_CONCEPTS + CASH_DEPOSITS_CONCEPTS + CASH_EQ_FALLBACK_CONCEPTS
        + CASH_EQ_CALL_LOANS_CONCEPTS + CASH_EQ_NONOP_SECURITIES_TOTAL_CONCEPTS + CASH_EQ_OPERATIONAL_SECURITIES_CONCEPTS
    )
    bs_local = set(local_name(x) for x in (bs_full | extra_full))

    prior_date_str, prior_ctx, cur_date_str, cur_ctx = choose_bs_contexts(
        facts, ctx_info, bs_full | extra_full, bs_local
    )

    v_full, v_local = facts_to_value_maps(facts)

    out: Dict[str, object] = {
        "bs_prior_date": prior_date_str,
        "bs_current_date": cur_date_str,
        "fy_end_month": extract_fy_end_month_from_dei(facts),
    }

    for field, concepts in BS_FIELDS.items():
        out[f"{field}_prior"] = first_value(v_full, v_local, concepts, prior_ctx)
        out[f"{field}_current"] = first_value(v_full, v_local, concepts, cur_ctx)

    out["cash_eq_st_invest_prior"] = calc_cash_eq_st_invest(v_full, v_local, prior_ctx)
    out["cash_eq_st_invest_current"] = calc_cash_eq_st_invest(v_full, v_local, cur_ctx)

    prior_d = parse_date_any(prior_date_str) if prior_date_str else None
    cur_d = parse_date_any(cur_date_str) if cur_date_str else None

    prior_ctx_debt = pick_best_debt_context(prior_d, prior_ctx, ctx_info, v_full, v_local)
    cur_ctx_debt   = pick_best_debt_context(cur_d, cur_ctx, ctx_info, v_full, v_local)

    # log用（WARN時に追えるように）
    out["debt_ctx_prior"] = prior_ctx_debt
    out["debt_ctx_current"] = cur_ctx_debt

    # debt components for each suffix (for rescue判断)
    for suffix, dctx in [("prior", prior_ctx_debt), ("current", cur_ctx_debt)]:
        comps = extract_debt_components_xbrl(v_full, v_local, dctx)
        for k in ["loans_cl", "bonds_cl", "cp_cl", "lease_cl", "st_total", "loans_ncl", "bonds_ncl", "lease_ncl", "lt_total"]:
            out[f"{k}_{suffix}"] = comps.get(k)

    out["short_term_borrowings_prior"] = out.get("st_total_prior")
    out["long_term_borrowings_prior"] = out.get("lt_total_prior")
    out["short_term_borrowings_current"] = out.get("st_total_current")
    out["long_term_borrowings_current"] = out.get("lt_total_current")

    out["shares_outstanding_prior"] = extract_shares(v_full, v_local, prior_ctx)
    out["shares_outstanding_current"] = extract_shares(v_full, v_local, cur_ctx)

    # ASRのみHTML補完（既存安定版）
    if doc_kind == "ASR" and html_candidates and cur_ctx_debt:
        _apply_html_additive_adjustment_for_asr(out, v_full, v_local, cur_ctx_debt, html_candidates)

    return out


# =============================
# TDNet scraping (fallback)
# =============================
def is_financial_results_title(title: str) -> bool:
    t = (title or "").replace("\xa0", " ").replace("\u3000", " ").strip()
    if not t:
        return False
    return any(p.search(t) for p in _FIN_RESULTS_PATTERNS)


def tdnet_fetch(session: requests.Session, url: str, timeout: int = 30) -> str:
    r = session.get(url, timeout=timeout)
    r.raise_for_status()
    r.encoding = r.apparent_encoding or "utf-8"
    return r.text


def tdnet_iter_daily_xbrl_zip_links(session: requests.Session, day: dt.date, target_tickers: set[str], max_pages: int = 200) -> List[dict]:
    ymd = day.strftime("%Y%m%d")
    out: List[dict] = []

    def clean(s: str) -> str:
        return (s or "").replace("\xa0", " ").replace("\u3000", " ").strip()

    code_pat = re.compile(r"^\d{4}[0-9A-Z]$", re.IGNORECASE)
    time_pat = re.compile(r"^\d{2}:\d{2}$")

    for p in range(1, max_pages + 1):
        url = urljoin(TDNET_BASE, f"I_list_{p:03d}_{ymd}.html")
        try:
            html = tdnet_fetch(session, url)
        except requests.HTTPError:
            break

        soup = BeautifulSoup(html, "html.parser")
        found_any_zip_in_page = False

        for tr in soup.find_all("tr"):
            zips = [a for a in tr.find_all("a", href=True) if a["href"].lower().endswith(".zip")]
            if not zips:
                continue
            found_any_zip_in_page = True

            tds = [clean(td.get_text(" ", strip=True)) for td in tr.find_all("td")]
            time_txt = tds[0] if len(tds) > 0 else ""
            code_txt = tds[1] if len(tds) > 1 else ""
            title_txt = tds[3] if len(tds) > 3 else ""

            if not time_pat.match(time_txt):
                continue
            if not code_pat.match(code_txt):
                continue

            code4 = code_txt[:4]
            if code4 not in target_tickers:
                continue

            if not is_financial_results_title(title_txt):
                continue

            out.append({
                "time": time_txt,
                "code": code_txt,
                "title": title_txt,
                "zip_urls": [urljoin(TDNET_BASE, a["href"]) for a in zips]
            })

        if not found_any_zip_in_page:
            break

    expanded = []
    for r in out:
        for zu in r["zip_urls"]:
            rr = dict(r)
            rr["zip_url"] = zu
            expanded.append(rr)
    return expanded


def scrape_tdnet_bs(target_tickers: set[str], days_back: int = 35, sleep_sec: float = 1.0, max_pages: int = 200) -> Dict[str, Dict[dt.date, dict]]:
    session = requests.Session()
    session.headers.update({"User-Agent": TDNET_UA})

    today_jst = (dt.datetime.utcnow() + dt.timedelta(hours=9)).date()
    start = today_jst - dt.timedelta(days=days_back)

    store: Dict[str, Dict[dt.date, dict]] = defaultdict(dict)
    seen_zip = set()

    for i in range(days_back + 1):
        day = start + dt.timedelta(days=i)
        try:
            items = tdnet_iter_daily_xbrl_zip_links(session, day=day, target_tickers=target_tickers, max_pages=max_pages)
        except Exception:
            items = []

        for it in items:
            zip_url = it.get("zip_url")
            if not zip_url or zip_url in seen_zip:
                continue
            seen_zip.add(zip_url)

            code4 = str(it.get("code", ""))[:4]
            if code4 not in target_tickers:
                continue

            try:
                zb = session.get(zip_url, timeout=60).content
                extracted = process_one_zip(zb, doc_kind=None)
            except Exception:
                continue
            finally:
                time.sleep(sleep_sec + random.random() * 0.4)

            try:
                hh, mm = [int(x) for x in (it.get("time") or "00:00").split(":")]
                as_of = dt.datetime(day.year, day.month, day.day, hh, mm)
            except Exception:
                as_of = dt.datetime(day.year, day.month, day.day, 0, 0)

            for suffix in ("prior", "current"):
                dstr = extracted.get(f"bs_{suffix}_date")
                d = parse_date_any(dstr) if dstr else None
                if not d:
                    continue

                rec = {
                    "source": "TDNet",
                    "doc_kind": "OTHER",
                    "suffix": suffix,
                    "as_of": as_of,
                    "title": it.get("title", ""),
                    "zip_url": zip_url,
                    "fy_end_month": extracted.get("fy_end_month"),
                    "assets_total": yen_to_million_3dp(extracted.get(f"assets_total_{suffix}")),
                    "current_assets": yen_to_million_3dp(extracted.get(f"current_assets_{suffix}")),
                    "cash_eq_st_invest": yen_to_million_3dp(extracted.get(f"cash_eq_st_invest_{suffix}")),
                    "current_liabilities": yen_to_million_3dp(extracted.get(f"current_liabilities_{suffix}")),
                    "short_term_borrowings": yen_to_million_3dp(extracted.get(f"short_term_borrowings_{suffix}")),
                    "long_term_borrowings": yen_to_million_3dp(extracted.get(f"long_term_borrowings_{suffix}")),
                    "income_taxes_payable": yen_to_million_3dp(extracted.get(f"income_taxes_payable_{suffix}")),
                    "shares_outstanding": extracted.get(f"shares_outstanding_{suffix}"),
        "debt_ctx": extracted.get(f"debt_ctx_{suffix}"),
                    "debt_ctx": extracted.get(f"debt_ctx_{suffix}"),
                }
                rec["_completeness"] = completeness_score(rec)

                prev = store[code4].get(d)
                if better_than(rec, prev):
                    store[code4][d] = rec

    return store


# =============================
# EDINET scraping (preferred) + ASR rescue
# =============================
_EDINET_DAY_CACHE: Dict[str, dict] = {}
_EDINET_DOC_EXTRACT_CACHE: Dict[str, dict] = {}
_ASR_RESCUE_DONE: set[Tuple[str, dt.date]] = set()  # (code4, period_end) 一度だけ


def edinet_get_documents(date: dt.date, api_key: str) -> dict:
    ds = date.isoformat()
    if ds in _EDINET_DAY_CACHE:
        return _EDINET_DAY_CACHE[ds]
    params = {"date": ds, "type": 2, "Subscription-Key": api_key}
    r = requests.get(EDINET_LIST_EP, params=params, timeout=60)
    r.raise_for_status()
    js = r.json()
    _EDINET_DAY_CACHE[ds] = js
    return js


def edinet_download_zip(docid: str, api_key: str) -> bytes:
    params = {"type": 1, "Subscription-Key": api_key}
    r = requests.get(EDINET_DOC_EP.format(docid=docid), params=params, timeout=120)
    r.raise_for_status()
    return r.content


def edinet_doc_kind(desc: str) -> str:
    d = desc or ""
    if "有価証券報告書" in d:
        return "ASR"
    if "四半期報告書" in d:
        return "QSR"
    if "半期報告書" in d:
        return "SSR"
    return "OTHER"


def edinet_is_financial_doc(rec: dict) -> bool:
    desc = str(rec.get("docDescription") or rec.get("docTypeName") or rec.get("docType") or "")
    keys = ["有価証券報告書", "四半期報告書", "半期報告書", "訂正有価証券報告書", "訂正四半期報告書", "訂正半期報告書"]
    return any(k in desc for k in keys)


def _parse_submit_datetime(rec: dict, fallback_day: dt.date) -> dt.datetime:
    submit_txt = str(rec.get("submitDateTime") or rec.get("submitDatetime") or rec.get("submitDate") or "")
    try:
        m = re.search(r"(\d{4}-\d{2}-\d{2})\s+(\d{2}:\d{2})", submit_txt)
        if m:
            return dt.datetime.fromisoformat(m.group(1) + " " + m.group(2))
    except Exception:
        pass
    return dt.datetime(fallback_day.year, fallback_day.month, fallback_day.day, 0, 0)


def _build_edinet_record_from_extracted(
    code4: str,
    desc: str,
    dk: str,
    docid: str,
    as_of: dt.datetime,
    extracted: dict,
    suffix: str,
    period_end: dt.date,
) -> dict:
    rec_out = {
        "source": "EDINET",
        "doc_kind": dk,
        "suffix": suffix,
        "as_of": as_of,
        "title": desc,
        "docID": docid,
        "fy_end_month": extracted.get("fy_end_month"),
        "assets_total": yen_to_million_3dp(extracted.get(f"assets_total_{suffix}")),
        "current_assets": yen_to_million_3dp(extracted.get(f"current_assets_{suffix}")),
        "cash_eq_st_invest": yen_to_million_3dp(extracted.get(f"cash_eq_st_invest_{suffix}")),
        "current_liabilities": yen_to_million_3dp(extracted.get(f"current_liabilities_{suffix}")),
        "short_term_borrowings": yen_to_million_3dp(extracted.get(f"short_term_borrowings_{suffix}")),
        "long_term_borrowings": yen_to_million_3dp(extracted.get(f"long_term_borrowings_{suffix}")),
        "income_taxes_payable": yen_to_million_3dp(extracted.get(f"income_taxes_payable_{suffix}")),
        "shares_outstanding": extracted.get(f"shares_outstanding_{suffix}"),
        "debt_ctx": extracted.get(f"debt_ctx_{suffix}"),
    }
    rec_out["_completeness"] = completeness_score(rec_out)
    return rec_out


def _ensure_asr_for_period_end_if_needed(
    store: Dict[str, Dict[dt.date, dict]],
    code4: str,
    period_end: dt.date,
    api_key: str,
) -> None:
    """
    SSR/QSRの prior で年度末期末が出てきたが、その期末ASRが走査期間外で拾えない場合だけ救済。
    既に試したら二度とやらない（キャッシュ）。
    """
    key = (code4, period_end)
    if key in _ASR_RESCUE_DONE:
        return
    _ASR_RESCUE_DONE.add(key)

    if not api_key:
        return

    start = period_end + dt.timedelta(days=ASR_RESCUE_START_DAYS)
    end = period_end + dt.timedelta(days=ASR_RESCUE_END_DAYS)

    # ざっくり period_end+30〜+200 を日次で探索（必要時のみ）
    day = start
    while day <= end:
        try:
            js = edinet_get_documents(day, api_key=api_key)
        except Exception:
            day += dt.timedelta(days=1)
            continue

        results = js.get("results") or js.get("Results") or []
        # その日の候補docid
        candidates = []
        for rec in results:
            sec = str(rec.get("secCode") or "")
            if not sec.startswith(code4):
                continue
            xflag = str(rec.get("xbrlFlag") or rec.get("xbrlFlg") or rec.get("xbrl") or "0")
            if xflag != "1":
                continue
            desc = str(rec.get("docDescription") or rec.get("docTypeName") or "")
            if "有価証券報告書" not in desc:
                continue
            docid = rec.get("docID") or rec.get("docId") or rec.get("docid")
            if not docid:
                continue
            candidates.append((rec, desc, docid))

        # 先に“訂正”より通常を優先
        candidates.sort(key=lambda x: (("訂正" in x[1]), x[1]))

        for rec, desc, docid in candidates[:6]:
            if docid in _EDINET_DOC_EXTRACT_CACHE:
                extracted = _EDINET_DOC_EXTRACT_CACHE[docid]
            else:
                try:
                    zb = edinet_download_zip(docid, api_key=api_key)
                    extracted = process_one_zip(zb, doc_kind="ASR")
                    _EDINET_DOC_EXTRACT_CACHE[docid] = extracted
                except Exception:
                    continue

            dcur = parse_date_any(extracted.get("bs_current_date"))
            if dcur != period_end:
                continue

            as_of = _parse_submit_datetime(rec, fallback_day=day)

            # ASRのprior/current両方をstoreに入れる（優先順位で勝つ）
            for suffix in ("prior", "current"):
                dstr = extracted.get(f"bs_{suffix}_date")
                d = parse_date_any(dstr) if dstr else None
                if not d:
                    continue
                rec_out = _build_edinet_record_from_extracted(
                    code4=code4,
                    desc=desc,
                    dk="ASR",
                    docid=docid,
                    as_of=as_of,
                    extracted=extracted,
                    suffix=suffix,
                    period_end=d,
                )
                prev = store[code4].get(d)
                if better_than(rec_out, prev):
                    store[code4][d] = rec_out

            return  # 見つかったので終了

        day += dt.timedelta(days=1)


def scrape_edinet_bs(target_tickers: set[str], days_back: int, api_key: str, sleep_sec: float = 1.0) -> Dict[str, Dict[dt.date, dict]]:
    if not api_key:
        raise ValueError("EDINET_API_KEY が空です。Colabで環境変数 EDINET_API_KEY を設定してください。")

    today_jst = (dt.datetime.utcnow() + dt.timedelta(hours=9)).date()
    scan_start = today_jst - dt.timedelta(days=days_back)

    store: Dict[str, Dict[dt.date, dict]] = defaultdict(dict)
    seen_doc = set()

    for i in range(days_back + 1):
        day = scan_start + dt.timedelta(days=i)

        try:
            js = edinet_get_documents(day, api_key=api_key)
        except Exception:
            time.sleep(sleep_sec)
            continue

        results = js.get("results") or js.get("Results") or []
        for rec in results:
            sec = str(rec.get("secCode") or "")
            code4 = sec[:4] if len(sec) >= 4 else ""
            if code4 not in target_tickers:
                continue

            xflag = str(rec.get("xbrlFlag") or rec.get("xbrlFlg") or rec.get("xbrl") or "0")
            if xflag != "1":
                continue

            if not edinet_is_financial_doc(rec):
                continue

            docid = rec.get("docID") or rec.get("docId") or rec.get("docid")
            if not docid or docid in seen_doc:
                continue
            seen_doc.add(docid)

            desc = str(rec.get("docDescription") or rec.get("docTypeName") or "")
            dk = edinet_doc_kind(desc)
            as_of = _parse_submit_datetime(rec, fallback_day=day)

            try:
                zb = edinet_download_zip(docid, api_key=api_key)
                extracted = process_one_zip(zb, doc_kind=dk)
            except Exception:
                time.sleep(sleep_sec)
                continue
            finally:
                time.sleep(sleep_sec + random.random() * 0.3)

            for suffix in ("prior", "current"):
                dstr = extracted.get(f"bs_{suffix}_date")
                d = parse_date_any(dstr) if dstr else None
                if not d:
                    continue

                rec_out = _build_edinet_record_from_extracted(
                    code4=code4,
                    desc=desc,
                    dk=dk,
                    docid=docid,
                    as_of=as_of,
                    extracted=extracted,
                    suffix=suffix,
                    period_end=d,
                )

                prev = store[code4].get(d)
                if better_than(rec_out, prev):
                    store[code4][d] = rec_out

                # ★v24.11 rescue:
                # SSR/QSRの prior が年度末(期末)で、かつその期末が走査開始日より前なら、ASRをオンデマンド探索して追加
                if dk in ("SSR", "QSR") and suffix == "prior":
                    fy_end_month = extracted.get("fy_end_month")
                    if isinstance(fy_end_month, int) and d.month == fy_end_month and d < scan_start:
                        _ensure_asr_for_period_end_if_needed(store, code4=code4, period_end=d, api_key=api_key)

    return store


def merge_stores_prefer_edinet(edinet_store: Dict[str, Dict[dt.date, dict]], tdnet_store: Dict[str, Dict[dt.date, dict]]) -> Dict[str, Dict[dt.date, dict]]:
    merged: Dict[str, Dict[dt.date, dict]] = defaultdict(dict)
    codes = set(tdnet_store.keys()) | set(edinet_store.keys())
    for code4 in codes:
        dates = set(tdnet_store.get(code4, {}).keys()) | set(edinet_store.get(code4, {}).keys())
        for d in dates:
            cand = []
            if d in tdnet_store.get(code4, {}):
                cand.append(tdnet_store[code4][d])
            if d in edinet_store.get(code4, {}):
                cand.append(edinet_store[code4][d])
            best = None
            for r in cand:
                if better_than(r, best):
                    best = r
            if best is not None:
                merged[code4][d] = best
    return merged


# =============================
# Excel mapping + fill
# =============================
def parse_fy_q(label: object) -> Optional[Tuple[int, int]]:
    if label is None:
        return None
    s = str(label).strip()
    m = re.search(r"(\d{4})年度第([1-4])四半期", s)
    if not m:
        return None
    return int(m.group(1)), int(m.group(2))


def build_col_map(ws, header_top: str) -> Dict[Tuple[int, int], int]:
    mp: Dict[Tuple[int, int], int] = {}
    for col in range(1, ws.max_column + 1):
        if str(ws.cell(1, col).value).strip() != header_top:
            continue
        fyq = parse_fy_q(ws.cell(2, col).value)
        if fyq:
            mp[fyq] = col
    return mp


def infer_fy_end_month_from_excel(ws, row: int, date_col_map: Dict[Tuple[int, int], int]) -> Optional[int]:
    q4_months: List[int] = []
    candidates: List[int] = []
    for (_fy, q), col in date_col_map.items():
        v = ws.cell(row, col).value
        ym = parse_yyyymm(v)
        if not ym:
            continue
        _y, m = ym
        end_m = ((m + (4 - q) * 3 - 1) % 12) + 1
        candidates.append(end_m)
        if q == 4:
            q4_months.append(m)
    if q4_months:
        return Counter(q4_months).most_common(1)[0][0]
    if candidates:
        return Counter(candidates).most_common(1)[0][0]
    return None


def fiscal_year_and_quarter(period_end_date: dt.date, fy_end_month: int) -> Tuple[int, int]:
    start_month = (fy_end_month % 12) + 1
    fy = period_end_date.year if (start_month == 1 or period_end_date.month >= start_month) else period_end_date.year - 1
    offset = (period_end_date.month - start_month) % 12
    q = (offset // 3) + 1
    return fy, max(1, min(4, q))


def collect_rows_and_tickers(path: str, max_rows: Optional[int]) -> Tuple[List[int], set[str]]:
    wb = load_workbook(path, read_only=True)
    ws = wb.active
    rows: List[int] = []
    tickers: set[str] = set()
    count = 0
    for r in range(4, ws.max_row + 1):
        v = ws.cell(r, 1).value
        if v is None:
            continue
        m = re.search(r"(\d{4})", str(v))
        if not m:
            continue
        rows.append(r)
        tickers.add(m.group(1))
        count += 1
        if max_rows is not None and count >= max_rows:
            break
    return rows, tickers


def fill_excel_from_store(
    input_xlsx: str,
    output_xlsx: str,
    store: Dict[str, Dict[dt.date, dict]],
    rows_to_process: List[int],
    warn_tolerance: Decimal = Decimal("1.0"),
    updated_color: str = "FFFFFF00",
    warning_color: str = "FFFFC000",
    verbose_warnings: bool = True,
) -> None:
    YELLOW = PatternFill(fill_type="solid", start_color=updated_color, end_color=updated_color)
    ORANGE = PatternFill(fill_type="solid", start_color=warning_color, end_color=warning_color)

    wb = load_workbook(input_xlsx)
    ws = wb.active

    CHECK_COL = column_index_from_string("EE")
    ws.cell(1, CHECK_COL).value = "懸念check"
    ws.cell(2, CHECK_COL).value = ws.cell(2, CHECK_COL).value or ""
    ws.cell(3, CHECK_COL).value = ws.cell(3, CHECK_COL).value or ""

    date_cols = build_col_map(ws, "決算期")
    col_assets = build_col_map(ws, "資産合計")
    col_cur_assets = build_col_map(ws, "流動資産")
    col_cash = build_col_map(ws, "現金同等物及び短期性有価証券")
    col_cur_liab = build_col_map(ws, "流動負債")
    col_st_debt = build_col_map(ws, "短期借入債務")
    col_lt_debt = build_col_map(ws, "長期借入債務")
    col_shares = build_col_map(ws, "期末発行済株式数 - 普通株")
    col_tax = build_col_map(ws, "未払法人税")

    field_to_cols = {
        "assets_total": col_assets,
        "current_assets": col_cur_assets,
        "cash_eq_st_invest": col_cash,
        "current_liabilities": col_cur_liab,
        "short_term_borrowings": col_st_debt,
        "long_term_borrowings": col_lt_debt,
        "shares_outstanding": col_shares,
        "income_taxes_payable": col_tax,
    }

    # 仕様変更：EE列「懸念check」は“直近5四半期”の橙色セル有無で判定する
    sorted_fyq = sorted(date_cols.keys())
    last5_fyq = set(sorted_fyq[-5:]) if len(sorted_fyq) >= 5 else set(sorted_fyq)

    warnings: List[str] = []
    filled = 0
    compared = 0
    warn_cells = 0
    row_has_warning_last5: Dict[int, bool] = defaultdict(bool)

    for row in rows_to_process:
        code_v = ws.cell(row, 1).value
        if code_v is None:
            continue
        m = re.search(r"(\d{4})", str(code_v))
        if not m:
            continue
        code4 = m.group(1)

        recs = store.get(code4)
        if not recs:
            ws.cell(row, CHECK_COL).value = ""
            continue

        excel_fy_end_month = infer_fy_end_month_from_excel(ws, row, date_cols)

        for period_end, rec in recs.items():
            fy_end_month = rec.get("fy_end_month")
            if not isinstance(fy_end_month, int) or not (1 <= fy_end_month <= 12):
                fy_end_month = excel_fy_end_month or 3

            fy, q = fiscal_year_and_quarter(period_end, fy_end_month)

            dcol = date_cols.get((fy, q))
            if dcol is not None:
                c = ws.cell(row, dcol)
                if is_blank_cell(c.value):
                    c.value = f"{period_end.year}/{period_end.month:02d}"
                    c.fill = YELLOW
                    filled += 1

            for field, cmap in field_to_cols.items():
                col = cmap.get((fy, q))
                if col is None:
                    continue
                new_val = rec.get(field)
                if new_val is None or new_val == "":
                    continue

                cell = ws.cell(row, col)
                old_val = cell.value

                if is_blank_cell(old_val):
                    cell.value = new_val
                    if field != "shares_outstanding" and isinstance(new_val, (int, float)) and has_fraction_3dp(float(new_val)):
                        cell.number_format = "#,##0.000"
                    cell.fill = YELLOW
                    filled += 1
                else:
                    old_d = to_decimal_safe(old_val)
                    new_d = to_decimal_safe(new_val)
                    if old_d is None or new_d is None:
                        continue
                    compared += 1
                    diff = (old_d - new_d).copy_abs()
                    if diff > warn_tolerance:
                        cell.fill = ORANGE
                        warn_cells += 1
                        in_last5 = (fy, q) in last5_fyq
                        if in_last5:
                            row_has_warning_last5[row] = True
                        warnings.append(
                            f"WARN {code4} R{row} C{col} field={field} fyq={fy}Q{q} in_last5={in_last5} existing={old_val} new={new_val} diff={diff} "
                            f"(period_end={period_end.isoformat()}, as_of={rec.get('as_of')}, source={rec.get('source')}, doc_kind={rec.get('doc_kind')}, suffix={rec.get('suffix')}, debt_ctx={rec.get('debt_ctx')}, title={rec.get('title','')})"
                        )

        ws.cell(row, CHECK_COL).value = 1 if row_has_warning_last5.get(row, False) else ""

    wb.save(output_xlsx)

    print(f"Done. filled_cells={filled}, compared_existing={compared}, warnings={len(warnings)}, warning_cells={warn_cells}")
    if verbose_warnings and warnings:
        print("\n".join(warnings[:200]))
        if len(warnings) > 200:
            print(f"... and {len(warnings)-200} more warnings")


# =============================
# Run (test)
# =============================
def main():
    rows_to_process, tickers = collect_rows_and_tickers(INPUT_XLSX, MAX_ROWS)
    print(f"Test mode rows={len(rows_to_process)} tickers={len(tickers)}")

    print("Scraping EDINET (preferred)...")
    edinet_store = scrape_edinet_bs(
        target_tickers=tickers,
        days_back=DAYS_BACK_EDINET,
        api_key=EDINET_API_KEY,
        sleep_sec=SLEEP_EDINET,
    )
    print(f"EDINET records: {sum(len(v) for v in edinet_store.values())}")

    print("Scraping TDNet (fallback)...")
    tdnet_store = scrape_tdnet_bs(
        target_tickers=tickers,
        days_back=DAYS_BACK_TDNET,
        sleep_sec=SLEEP_TDNET,
        max_pages=200,
    )
    print(f"TDNet records: {sum(len(v) for v in tdnet_store.values())}")

    merged = merge_stores_prefer_edinet(edinet_store, tdnet_store)
    print(f"Merged records: {sum(len(v) for v in merged.values())}")

    fill_excel_from_store(
        input_xlsx=INPUT_XLSX,
        output_xlsx=OUTPUT_XLSX,
        store=merged,
        rows_to_process=rows_to_process,
        warn_tolerance=WARN_TOLERANCE,
        verbose_warnings=True,
    )
    print(f"Saved: {OUTPUT_XLSX}")


if __name__ == "__main__":
    main()

